{% set name = "aws-c-mqtt" %}
{% set version = "0.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1dfc11d6b3dc1a6d408df64073e8238739b4c50374078d36d3f2d30491d15527

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-mqtt", max_pin="x.x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cmake >=3.9
    - ninja-base
  host:
    - aws-c-common 0.12.4
    - aws-c-io 0.21.4
    - aws-c-http 0.10.4

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-mqtt${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/mqtt/mqtt.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\mqtt\\mqtt.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\aws-c-mqtt.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-mqtt
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the MQTT
  description: |
    C99 implementation of the MQTT 3.1.1 and MQTT 5 specifications.
  dev_url: https://github.com/awslabs/aws-c-mqtt
  doc_url: https://github.com/awslabs/aws-c-mqtt

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
