{% set name = "aws-c-mqtt" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8d22b181e4c90f5c683e786aadb9fb59a30a699c332e96e16595216ef9058c2f

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-mqtt", max_pin="x.x.x") }}

requirements:
  build:
    - cmake >=3.9
    - {{ compiler('c') }}
    - ninja-base
  host:
    - aws-c-common 0.12.3
    - aws-c-io 0.20.1
    - aws-c-http 0.10.2

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-mqtt${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/mqtt/mqtt.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\mqtt\\mqtt.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-mqtt.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-mqtt
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the MQTT
  description: |
    C99 implementation of the MQTT 3.1.1 and MQTT 5 specifications.
  dev_url: https://github.com/awslabs/aws-c-mqtt
  doc_url: https://github.com/awslabs/aws-c-mqtt

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
